
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#    url: jdbc:mysql://10.100.164.5:3306/campus?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 10.100.164.5
    port: 6379
  mvc:
#    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher

  rabbitmq:
#    host: 10.100.164.5
    host: localhost
    username: guest
    password: guest
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-value: 1
      logic-not-delete-value: 0


#自定义
global:
  rankSize: 20
#  ip: 192.168.1.100
  ip: 10.41.182.53
#  ip: 10.100.164.5
  file-path-window: file:/D:/IDEA/ideaProjects/SpringBoot/Demo03/target/pictures/
  file-path-linux: file:/pictures/
